org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8
org.gradle.java.home=C:\\Program Files\\Eclipse Adoptium\\jdk-21.0.9.10-hotspot
org.gradle.parallel=true
org.gradle.configuration-cache=true
android.useAndroidX=true
android.enableJetifier=false
android.nonTransitiveRClass=true
android.overridePathCheck=true
kotlin.code.style=official
kapt.use.k2=true
